apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: product-service
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: product
  labels:
    app: product-service
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product
          image: sherjeelghouse/product
          ports:
            - containerPort: 8080
              name: api